### ISSUE TITLE
MAKER failing to annotate long contigs

### ISSUE THREAD

**Issue by okendojo** [Yandell-Lab/maker#9] opened 2023-01-24 15:50 UTC
Maker is failing to annotate on of my contig which is 24mbps when I switchon evidence modeler. What could be the problem?  That contig is throwing the following error:

```bash
ERROR: evm failed
--> rank=29, hostname=cn0700
ERROR: Failed while preparing evidence clusters for annotations
ERROR: Chunk failed at level:0, tier_type:4
FAILED CONTIG:ptg000009l
```
I am also getting the following error in my logfile and I am not sure how to go about it. 
```
DBD::SQLite::db selectcol_arrayref failed: database is locked at /usr/local/apps/MAKER/3.01.03/maker/bin/../lib/GFFDB.pm
```

**Comment by carsonhh** [comment] 2024-01-15 16:55
Closing older issue. This is caused by Setting TMP= to a network mounted or in memory location. It must be set to a local disk for each node, otherwise you get IO race condition on file locks

**Closed as completed** 2024-01-15 16:55 UTC
